stages:
  - build                # Build binaries
  - sanitation           # Execute some sanitation tests on the code
  - doc                  # Generates the documentation
  - packaging            # Packages the project

#===========================================================================
# TEMPLATES
#===========================================================================
.build_template: &build_definition
  stage: build
  before_script:
    - cmake -E remove_directory build
    - cmake -E make_directory build
  script:
    - cmake -E chdir build cmake -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build build
  allow_failure: false

.package_template: &package_definition
  stage: packaging
  before_script:
    - cmake -E remove_directory build
    - cmake -E make_directory build
    - cmake -E rename build-doc/generated_doc build/generated_doc
  script:
    - cmake -E chdir build cmake -DCMAKE_BUILD_SHARED_LIBS=ON -DBUILD_DOC=ON -DBUILD_PACKAGE=ON -DCMAKE_BUILD_TYPE=Release ..
    - cmake -E chdir build cmake --build . --target package
  dependencies:
    - doc:generate api
  only:
    - develop
    - master

.sanitation:no warnings: &no_warns_definition
  stage: sanitation
  before_script:
    - cmake -E remove_directory build
    - cmake -E make_directory build
  script:
    - cmake -E chdir build cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra" ..
    - cmake --build build

#===========================================================================
# BUILD 
#===========================================================================
build:osx:
  <<: *build_definition
  artifacts:
    paths:
      - build/libmapgen.*dylib*
      - build/test/biometexgen
      - build/test/noisetexgen
    expire_in: 1 week
  tags:
    - osx
build:linux:gcc:
  <<: *build_definition
  script:
    - cmake -E chdir build cmake -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..
    - cmake --build build
  artifacts:
    paths:
      - build/libmapgen.*so*
      - build/test/biometexgen
      - build/test/noisetexgen
    expire_in: 1 week
  tags:
    - linux
build:linux:clang:
  <<: *build_definition
  script:
    - cmake -E chdir build cmake -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
    - cmake --build build
  artifacts:
    paths:
      - build/libmapgen.*so*
      - build/test/biometexgen
      - build/test/noisetexgen
    expire_in: 1 week
  tags:
    - linux
build:windows:
  <<: *build_definition
  script:
      - cmake -E chdir build cmake -DBUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release ..
      - cmake --build build
  artifacts:
    paths:
      - build\Debug\mapgen.lib
      - build\Debug\mapgen.pdb
      - build\test\Debug\biometexgen.exe
      - build\test\Debug\noisetexgen.exe
    expire_in: 1 week
  tags:
    - windows

#===========================================================================
# SANITATION
#===========================================================================
# Failure is allowed on branches that aren't master
sanitation:no warnings:linux:gcc:
  <<: *no_warns_definition
  allow_failure: true
  except:
    - master
    - develop
  tags:
    - linux
    - gcc

sanitation:no warnings:linux:clang:
  <<: *no_warns_definition
  allow_failure: true
  except:
    - master
    - develop
  tags:
    - linux
    - clang

# Failure is not allowed on master
#sanitation:no warnings:linux:gcc:
#  <<: *no_warns_definition
#  only:
#    - master
#    - develop
#  tags:
#    - linux
#    - gcc

#sanitation:no warnings:linux:clang:
#  <<: *no_warns_definition
#  only:
#    - master
#    - develop
#  tags:
#    - linux
#    - clang

#===========================================================================
# DOCUMENTATION
#===========================================================================
doc:generate api:
  stage: doc
  before_script:
    - cmake -E remove_directory build-doc
    - cmake -E make_directory build-doc
  script:
    - cmake -E chdir build-doc cmake -DBUILD_DOC=ON ..
    - cmake --build build-doc --target doc
  artifacts:
    paths:
      - build-doc/generated_doc
    expire_in: 1 week
  dependencies: []
  tags:
    - documentation
  only:
    - develop
    - master

#===========================================================================
# PACKAGING
#===========================================================================
packaging:linux:
  <<: *package_definition
  artifacts:
    paths:
      - build/MapGeneration-*-Linux.sh
      - build/MapGeneration-*-Linux.tar.gz
      - build/MapGeneration-*-Linux.tar.Z
    expire_in: 1 week
  tags:
    - linux

packaging:osx:
  <<: *package_definition
  artifacts:
    paths:
    - build/MapGeneration-*-Darwin.sh
    - build/MapGeneration-*-Darwin.tar.gz
    expire_in: 1 week
  tags:
    - osx

packaging:windows:
  <<: *package_definition
  artifacts:
    paths:
    - build/MapGeneration-*-win32.exe
    expire_in: 1 week
  tags:
    - windows