stages:
  - build
  - doc

build:linux:gcc:
  stage: build
  before_script:
    - cmake -E remove_directory build-debug
    - cmake -E make_directory build-debug
  script:
    - CC=gcc CXX=g++ cmake -E chdir build-debug cmake -DBUILD_SHARED_LIBS=ON ..
    - cmake -E chdir build-debug cmake --build .
  artifacts:
    paths:
      - build-debug/libmapgen.so*
    expire_in: 1 week
  tags:
    - linux
  allow_failure: false
build:linux:clang:
  stage: build
  before_script:
    - cmake -E remove_directory build-debug
    - cmake -E make_directory build-debug
  script:
    - CC=clang CXX=clang++ cmake -E chdir build-debug cmake -DBUILD_SHARED_LIBS=ON ..
    - cmake -E chdir build-debug cmake --build .
  artifacts:
    paths:
      - build-debug/libmapgen.so*
    expire_in: 1 week
  tags:
    - linux
  allow_failure: false

build:windows:
  stage: build
  before_script:
    - cmake -E remove_directory build-debug
    - cmake -E make_directory build-debug
  script:
    - cmake -E chdir build-debug cmake -DBUILD_SHARED_LIBS=ON ..
    - cmake -E chdir build-debug cmake --build .
  artifacts:
    paths:
      - build-debug\Debug\mapgen.dll
      - build-debug\Debug\mapgen.pdb
      - build-debug\Debug\mapgen.ilk
    expire_in: 1 week
  tags:
    - windows
  allow_failure: false

doc:generate api:
  stage: doc
  before_script:
    - cmake -E remove_directory build-doc
    - cmake -E make_directory build-doc
  script:
    - cmake -E chdir build-doc cmake -DBUILD_DOC=ON ..
    - cmake -E chdir build-doc cmake --build . --target doc
  tags:
    - documentation
