stages:
  - build
  - doc
  - deployment

#===========================================================================
# TEMPLATES
#===========================================================================
.build_template: &build_definition
  stage: build
  before_script:
    - cmake -E remove_directory build-debug
    - cmake -E make_directory build-debug
  script:
    - cmake -E chdir build-debug cmake -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=ON ..
    - cmake -E chdir build-debug cmake --build .
  allow_failure: false

#===========================================================================
# BUILD 
#===========================================================================
build:osx:
  <<: *build_definition
  artifacts:
    paths:
      - build-debug/libmapgen.*dylib*
      - build-debug/test/biometexgen
      - build-debug/test/noisetexgen
    expire_in: 1 week
  tags:
    - osx
build:linux:gcc:
  <<: *build_definition
  script:
    - CC=gcc CXX=g++ cmake -E chdir build-debug cmake -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=ON ..
    - cmake -E chdir build-debug cmake --build .
  artifacts:
    paths:
      - build-debug/libmapgen.*so*
      - build-debug/test/biometexgen
      - build-debug/test/noisetexgen
    expire_in: 1 week
  tags:
    - linux
build:linux:clang:
  <<: *build_definition
  script:
    - CC=clang CXX=clang++ cmake -E chdir build-debug cmake -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=ON ..
    - cmake -E chdir build-debug cmake --build .
  artifacts:
    paths:
      - build-debug/libmapgen.*so*
      - build-debug/test/biometexgen
      - build-debug/test/noisetexgen
    expire_in: 1 week
  tags:
    - linux
build:windows:
  <<: *build_definition
  script:
      - cmake -E chdir build-debug cmake -DBUILD_TEST=ON ..
      - cmake -E chdir build-debug cmake --build .
  artifacts:
    paths:
      - build-debug\Debug\mapgen.lib
      - build-debug\Debug\mapgen.pdb
      - build-debug\test\Debug\biometexgen.exe
      - build-debug\test\Debug\noisetexgen.exe
    expire_in: 1 week
  tags:
    - windows

#===========================================================================
# DOCUMENTATION
#===========================================================================
doc:generate api:
  stage: doc
  before_script:
    - cmake -E remove_directory build-doc
    - cmake -E make_directory build-doc
  script:
    - cmake -E chdir build-doc cmake -DBUILD_DOC=ON ..
    - cmake -E chdir build-doc cmake --build . --target doc
  artifacts:
    paths:
      - build-doc/generated_doc
    expire_in: 1 week
  tags:
    - documentation
  only:
    - develop
    - master

#===========================================================================
# DEPLOYMENT
#===========================================================================
deployment:develop:
  stage: deployment
  dependencies:
    - build:osx
    - build:windows
    - build:linux:gcc
    - build:linux:clang
    - doc:generate api
  script:
    - ./script/deploy $CI_COMMIT_SHA
  tags:
    - deployment
  only:
    - develop